name: App
options:
  deploymentTarget:
    iOS: 13.2
  developmentRegion: en
settings:
  BUNDLE_BUILD_VERSION: 1.0.0.0
  BUNDLE_VERSION: 1.0.0
  SWIFT_VERSION: 5.1
settingGroups:
  automatic_signing:
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: Y3FSN97W3M
targets:
  App:
    type: application
    platform: iOS
    devices: [iPhone, iPad]
    settings:
      ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: ${inherited}
      groups: [automatic_signing]
      base:
        IPHONEOS_DEPLOYMENT_TARGET: 13.2
        PRODUCT_BUNDLE_IDENTIFIER: com.share.extension.App
    attributes:
      ProvisioningStyle: Automatic
    info:
      path: App/Info.plist
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait, UIInterfaceOrientationPortraitUpsideDown, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
        UILaunchStoryboardName: LaunchScreen
    entitlements:
      path: App/App.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.share.extension.App
        keychain-access-groups:
          - $(AppIdentifierPrefix)com.share.extension.App
    sources:
      - path: App
    dependencies:
      - target: Share
        embed: true
        codeSign: false
  Share:
    type: app-extension
    platform: iOS
    devices: [iPhone, iPad]
    settings:
      groups: [automatic_signing]
      base:
        IPHONEOS_DEPLOYMENT_TARGET: 13.2
        PRODUCT_BUNDLE_IDENTIFIER: com.share.extension.App.Share
    attributes:
      ProvisioningStyle: Automatic
    info:
      path: Share/Info.plist
      properties:
        CFBundleDisplayName: Share
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        NSExtension:
          NSExtensionAttributes:
            NSExtensionActivationRule:
              SUBQUERY (
                  extensionItems,
                  $extensionItem,
                  SUBQUERY (
                      $extensionItem.attachments,
                      $attachment,
                      ANY $attachment.registeredTypeIdentifiers UTI-CONFORMS-TO "public.url"
                  ).@count == $extensionItem.attachments.@count
              ).@count == 1
          NSExtensionMainStoryboard: "MainInterface"
          NSExtensionPointIdentifier: "com.apple.share-services"
    entitlements:
      path: Share/Share.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.share.extension.App
        keychain-access-groups:
          - $(AppIdentifierPrefix)com.share.extension.App
    sources:
      - path: Share
  AppTests:
    type: bundle.unit-test
    platform: iOS
    settings:
      base:
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: Y3FSN97W3M
        PRODUCT_BUNDLE_IDENTIFIER: com.share.extension.AppTests
    info:
      path: AppTests/Info.plist
    sources: AppTests
    dependencies:
      - target: App
schemes:
  App:
    build:
      targets:
        App: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - name: AppTests
          parallelizable: true
          randomExecutionOrder: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
      customArchiveName: App
      revealArchiveInOrganizer: true
  Share:
    build:
      targets:
        Share: all
        App: all
    run:
      config: Debug
      askForAppToLaunch: true
      environmentVariables:
        OS_ACTIVITY_MODE: disable
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - name: Share
          parallelizable: true
          randomExecutionOrder: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
      customArchiveName: App
      revealArchiveInOrganizer: true
